FROM ubuntu

WORKDIR /home

COPY /Users/tejaslolage/Documents/Programming/Projects/OnlineJudgeProject/onlinejudge/oj/coderunner /home/

WORKDIR /home/coderunner

RUN apt update

RUN apt install g++

RUN apt install python3