# Generated by Django 4.0.5 on 2022-06-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemStatement', models.CharField(max_length=500)),
                ('ProblemName', models.CharField(max_length=50)),
                ('UserCode', models.CharField(max_length=10000)),
                ('ProblemDifficulty', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=300)),
                ('Output', models.CharField(max_length=300)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=300)),
                ('submitted_at', models.DateTimeField(verbose_name='time of submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.problems')),
            ],
        ),
    ]
