# Generated by Django 4.0.5 on 2022-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='ProblemName',
            new_name='problemName',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='ProblemDifficulty',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='UserCode',
        ),
        migrations.AddField(
            model_name='problems',
            name='problemDifficulty',
            field=models.CharField(default='trials', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutions',
            name='userCode',
            field=models.CharField(default='int main(){return 0;}', max_length=10000),
            preserve_default=False,
        ),
    ]
