# Generated by Django 4.0.5 on 2022-07-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_rename_problemname_problems_problemname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='Test_cases',
            new_name='TestCase',
        ),
    ]
