# Generated by Django 4.0.5 on 2022-08-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_rename_problems_problem_rename_solutions_solution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userCode', models.CharField(max_length=10000)),
                ('verdict', models.CharField(max_length=300)),
                ('submitted_at', models.DateTimeField(verbose_name='time of submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
