# Generated by Django 4.0.5 on 2022-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_usersubmission_delete_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='compiler',
            field=models.CharField(choices=[('Select', 'Select your desired compiler'), ('GNU G++ 17', 'C++'), ('Java', 'Java'), ('Python 3', 'Python')], default='Select', max_length=20),
        ),
    ]
