# Generated by Django 4.0.5 on 2022-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0008_remove_usersubmission_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userEmail',
            field=models.EmailField(default='a@mail.com', max_length=100),
            preserve_default=False,
        ),
    ]
