# Generated by Django 4.0.5 on 2022-08-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0009_userdata_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Input',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Output',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
