# Generated by Django 4.0.5 on 2022-08-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0010_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OJ.userdata'),
            preserve_default=False,
        ),
    ]
