# Generated by Django 4.1.7 on 2023-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0012_alter_usersubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problemName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problemStatement',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Input',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Output',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='compiler',
            field=models.CharField(choices=[('Select', 'Select your desired compiler'), ('GNU G++ 17', 'C++'), ('Java', 'Java'), ('Python 3', 'Python')], default='Select', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='userCode',
            field=models.CharField(max_length=100000),
        ),
    ]
